MvcCoreStorage/Models/BlobModel.cs
namespace MvcCoreStorage.Models
{
    public class BlobModel
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Contenedor { get; set; }

    }
}

MvcCoreStorage/Models/ErrorViewModel.cs
namespace MvcCoreStorage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreStorage/Controllers/AzureBlobsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreStorage.Models;
using MvcCoreStorage.Services;

namespace MvcCoreStorage.Controllers
{
    public class AzureBlobsController : Controller
    {
        private ServiceStorageBlobs service;

        public AzureBlobsController(ServiceStorageBlobs service)
        {
            this.service = service;
        }

        public async Task<IActionResult> ListContainers()
        {
            List<string> containers = await this.service.GetContainersAsync();
            return View(containers);
        }

        public IActionResult CreateContainer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateContainer(string containerName)
        {
            await this.service.CreateContainerAsync(containerName);
            return RedirectToAction("ListContainers");
        }

        public async Task<IActionResult> DeleteContainer(string containerName)
        {
            await this.service.DeleteContainerAsync(containerName);
            return RedirectToAction("ListContainers");
        }

        public async Task<IActionResult> ListBlobs(string containerName)
        {
            List<BlobModel> blobModels =
                await this.service.GetBlobsAsync(containerName);
            return View(blobModels);
        }

        public async Task<IActionResult> DeleteBlob
            (string containerName, string blobName)
        {
            await this.service.DeleteBlobAsync(containerName, blobName);
            return RedirectToAction
                ("ListBlobs", new { containerName = containerName });
        }

        public IActionResult UploadBlob(string containerName)
        {
            ViewData["CONTAINER"] = containerName;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadBlob
            (string containerName, IFormFile file)
        {
            string blobName = file.FileName;
            using(Stream stream = file.OpenReadStream())
            {
                await this.service.UploadBlobAsync
                    (containerName, blobName, stream);
            }
            return RedirectToAction
                ("ListBlobs", new { containerName = containerName });
        }
    }
}

MvcCoreStorage/Controllers/AzureFilesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreStorage.Services;

namespace MvcCoreStorage.Controllers
{
    public class AzureFilesController : Controller
    {
        private ServiceStorageFiles service;

        public AzureFilesController(ServiceStorageFiles service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<string> files = await this.service.GetFilesAsync();
            return View(files);
        }

        public async Task<IActionResult> ReadFile(string filename)
        {
            string data = await this.service.ReadFilesAsync(filename);
            ViewData["DATA"] = data;
            return View();
        }

        public async Task<IActionResult> DeleteFile(string filename)
        {
            await this.service.DeleteFilesAsync(filename);
            return RedirectToAction("Index");
        }

        public IActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            string fileName = file.FileName;
            using (Stream stream = file.OpenReadStream())
            {
                await this.service.UploadFileAsync(fileName, stream);
            }
            ViewData["MENSAJE"] = "Fichero subido correctamente";
            return View();
        }
    }
}

MvcCoreStorage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreStorage.Models;
using System.Diagnostics;

namespace MvcCoreStorage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreStorage/Views/AzureBlobs/CreateContainer.cshtml
<h1 style="color: red">
    New Azure Container
</h1>

<form method="post">
    <label>Nombre del contenedor: </label>
    <input type="text" name="containername"
        class="form-control" />
    <button class="btn btn-info">
        Create
    </button>
</form>

MvcCoreStorage/Views/AzureBlobs/ListBlobs.cshtml
@model List<BlobModel>

<h1>
    List Blobs
</h1>

<ul class="list-group">
    @foreach(BlobModel blob in Model)
    {
        <li class="list-group-item">
            @blob.Nombre
            <img src="@blob.Url" style="width: 150px; height: 150px" />
            <a asp-controller="AzureBlobs" asp-action="DeleteBlob"
                asp-route-containername="@blob.Contenedor"
                asp-route-blobname="@blob.Nombre"
                class="btn btn-danger">
                Delete blob
            </a>
        </li>
    }
</ul>

MvcCoreStorage/Views/AzureBlobs/ListContainers.cshtml
@model List<string>

<h1 style="color: blue">
    Azure Storage Containers
</h1>

<a asp-controller="AzureBlobs" asp-action="CreateContainer">
    Create Container
</a>

@if(Model != null)
{
    <ul class="list-group">
        @foreach(string container in Model)
        {
            <li class="list-group-item">
                @container
            </li>
            <br/>
            <a asp-controller="AzureBlobs"
                asp-action="ListBlobs"
                asp-route-containername="@container"
                class="btn btn-info">
                Blobs
            </a>
            <a asp-controller="AzureBlobs"
                asp-action="UploadBlob"
                asp-route-containername="@container"
                class="btn btn-outline-primary">
                Upload Blobs
            </a>
            <a asp-controller="AzureBlobs"
                asp-action="DeleteContainer"
                asp-route-containername="@container"
                class="btn btn-danger">
                Delete Container
            </a>
        }
    </ul>
}

MvcCoreStorage/Views/AzureBlobs/UploadBlob.cshtml
<h1 style="color: blueviolet">
    Upload Blob
</h1>

<form method="post" enctype="multipart/form-data">
    <label>Seleccione un fichero: </label>
    <input type="file" name="file" />
    <input type="hidden" name="containername"
        value="@ViewData["CONTAINER"]" />
    <button class="btn btn-dark">
        Upload file
    </button>
</form>

MvcCoreStorage/Views/AzureFiles/Index.cshtml
@model List<string>

<h1>Azure Storage Files</h1>

<a asp-controller="AzureFiles"
    asp-action="UploadFile">
    Upload File
</a>

@if(Model != null){
    <ul class="list-group">
        @foreach(string fileName in Model)
        {
            <li class="list-group-item">
                @fileName
                <a asp-controller="AzureFiles" asp-action="ReadFile"
                    asp-route-filename="@fileName"
                    class="btn btn-info">
                    Read
                </a>
                <a asp-controller="AzureFiles" asp-action="DeleteFile"
                    asp-route-filename="@fileName"
                    class="btn btn-danger">
                    Delete
                </a>
            </li>
        }
    </ul>
}

MvcCoreStorage/Views/AzureFiles/ReadFile.cshtml
<h1>Read File</h1>

<a asp-controller="AzureFiles" asp-action="Index">
    Volver a Index
</a>

<p style="color: blueviolet; font-size: large">
    @ViewData["DATA"]
</p>

MvcCoreStorage/Views/AzureFiles/UploadFile.cshtml
<h1>Upload Azure Storage File</h1>

<a asp-controller="AzureFiles" asp-action="Index">
    Volver a Index
</a>

<form method="post" enctype="multipart/form-data">
    <label>Seleccione fichero: </label>
    <input type="file" name="file" />
    <button class="btn btn-info">
        Upload file
    </button>
</form>

<h2 style="color: red">
    @ViewData["MENSAJE"]
</h2>

MvcCoreStorage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreStorage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreStorage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreStorage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AzureFiles" asp-action="Index">Azure Files</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AzureBlobs" asp-action="ListContainers">Azure Blobs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreStorage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>